# Generated by Django 5.2.7 on 2025-10-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSASite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(0, 'multipleChoice'), (1, 'dragAndDrop'), (2, 'scenario')]),
        ),
        migrations.CreateModel(
            name='TaskDropFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSSASite.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDropOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSSASite.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDropEvaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness', models.IntegerField(default=0)),
                ('drop_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSSASite.taskdropfieldoption')),
                ('drop_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSSASite.taskdropoption')),
            ],
        ),
    ]
