# Generated by Django 5.2.7 on 2025-10-18 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSASite', '0002_alter_task_task_type_taskdropfieldoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='knowledge_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CSSASite.knowledgedomain'),
            preserve_default=False,
        ),
    ]
