# Generated by Django 5.2.7 on 2025-10-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSASite', '0003_task_knowledge_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDropEvaluations',
            new_name='TaskDropEvaluation',
        ),
    ]
