# Generated by Django 5.2.7 on 2025-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSASite', '0004_rename_taskdropevaluations_taskdropevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='response_time',
            field=models.FloatField(),
        ),
    ]
