# Generated by Django 5.2.7 on 2025-10-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSSASite', '0005_alter_taskcompletion_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='overall_task_score',
        ),
    ]
